### ISSUE TITLE
Use float arithmetic when should use integer arithmetic

### ISSUE THREAD

**Issue by Yehouda** [sharplispers/parse-number#12]
https://github.com/sharplispers/parse-number/blob/de944fd22c9e5db450d48cdf829abd38a375c07c/parse-number.lisp#L256

The code for **make-float/whole** does floating-point arithmetic when it should do integer arithmetic, which can lose precision. It should do all computation in integers, and then coerce to float,  somehing like:
```
(let ((integer-value (* (number-value whole-place)
                                 (expt 10 
                                     (number-value exp-place))))
     (type (type-for-exponent-marker exp-marker))
 (coerce integer-value type))
```

**make-float/frac** should do the same, compute a ratio number, and then coerce.

running on LispWorks:
```
CL-USER 113 > (read-from-string "5d50")
(read-from-string "5d50")
5.0D50
4

CL-USER 114 > (parse-number:parse-number "5d50")
(parse-number:parse-number "5d50")
5.000000000000027D50
```

Should also add large exponents to the tests.

**Comment by sionescu** [comment]
Thank you.

Fixed by 715ae01d378a.
