### ISSUE TITLE
License

### ISSUE THREAD

**Issue by malisper** [sharplispers/parse-number#6]
I noticed that in parse-number.lisp it says that the project is public domain, yet parse-number.lisp has the BSD-3 at the top.

Is the project in the public domain or is it under the BSD-3?

**Comment by luismbo** [comment]
git blame says @sionescu added the "public domain" metadata to the .asd file. It seems more likely that the author placed the library under BSD-3. @sionescu, any objections to fixing the .asd file?

**Comment by sionescu** [comment]
No objection

**Comment by luismbo** [comment]
There we go. Thanks @malisper.
